
[default.general]
chip = "nrf52833_xxAA"

[default.reset]
halt_afterwards = false

[default.rtt]
enabled = true

up_channels = [
    { channel = 0, format = "String", show_timestamps = false },
]

[default.gdb]
enabled = false
